### ISSUE TITLE
Setup Travis-CI for build AppImage

### ISSUE THREAD

**Issue by ghost** [Laidout/laidout#10]
Cast @probonopd

**Comment by probonopd** [comment]
First thing to do: Get it to build on Travis CI on Ubuntu 14.04.

> Ubuntu 14.04 needs a more recent harfbuzz than is included, but more recent Ubuntu should work well.

This is worrisome, as bundling Harfbuzz inside the AppImage is known to be problematic (see https://github.com/probonopd/linuxdeployqt/issues/261#issuecomment-377522251 and https://github.com/probonopd/linuxdeployqt/issues/157#issuecomment-320755694).

Options:
* Remove the dependency on Harfbuzz
* Lower the dependency on Harfbuzz to the one in 14.04
* Statically link Harfbuzz

**Comment by probonopd** [comment]
Tried it at https://github.com/probonopd/laidout/blob/patch-1/.travis.yml. As was to be expected, running into 

```
captioninterface.cc:428:49: error: ‘hb_ft_face_create_referenced’ was not declared in this scope
   hb_face = hb_ft_face_create_referenced(ft_face); 
```

https://travis-ci.org/probonopd/laidout/builds/374735928#L718

This code is too new to work on the oldest still-supported version of Ubuntu, which currently is 14.04. The source code needs to be changed so that it can build on 14.04. Otherwise the AppImage will not run on all still-supported versions of the major distributions (which one usually wants). With other libraries, the solution would be to just bundle the library in question, but this does not work properly with libharfbuzz for some reason.

**Comment by tomlechner** [comment]
Laidout 0.096 doesn't really need very current harfbuzz stuff, I don't recall this being insurmountable a couple years ago, meaning it shouldn't be all that difficult to make it work on default 14.04. I'm travelling now, but I'll look into it when I get home in a few days, unless you can patch it! However, I no longer have a 14.04 to test.

FYI I hope to have a 0.097 release within a month or so, and I'll be testing on Ubuntu 16.04, but it will likely be very difficult to make it work with default 14.04 harfbuzz.

**Comment by tomlechner** [comment]
Been low on free time, I would expect an AppImage that works on 14.04 to be successful with the "stable" Laidout 0.096 version as that does not depend on harfbuzz at all. Immediately after 0.096, I started using harfbuzz, and newer harfbuzz provides too many improvements to justify supporting 14.04 at this point. But I'd be happy to set up a separate branch if someone has a patch!

**Comment by ghost** [comment]
>  I started using harfbuzz, and newer harfbuzz provides too many improvements

Which version of `harfbuzz` you mean?

> But I'd be happy to set up a separate branch if someone has a patch!

Need ask Trusty-backports team

- https://bugs.launchpad.net/trusty-backports
- https://launchpad.net/trusty-backports

There are many other guys that provide backports for Trusty on Launchpad, so will try cast some of them

- https://launchpad.net/~jonathonf/+archive/ubuntu/backports/+packages
- https://launchpad.net/~mscore-ubuntu/+archive/ubuntu/mscore-stable/+packages
- https://launchpad.net/~jonathonf/+archive/ubuntu/texlive/+packages
- ...
- https://launchpad.net/+search?field.text=harfbuzz

**Comment by tomlechner** [comment]
For the upcoming Laidout 0.097, I'll make it work on default Ubuntu 16.04. My text tools are very much works in progress, and my goal is to support as many writing systems as I can. I'm certainly no expert, but it seems like the most current harfbuzz as possible is important for that. Balancing new development against old system compatibility is not easy.

For backporting, I would think the first step is getting any version of Laidout in a Debian or Ubuntu repository at all, currently it's not, as far as I know. I would very much welcome that, but I don't personally have enough free time to take that on.

**Comment by probonopd** [comment]
Tried building Laidout, but running into issues:

```
./configure --laxkit=`pwd`/laxkit/lax --prefix=/usr --nogl --disable-sqlite --force
Checking for x11......ok
Checking for xext......ok
Checking for freetype2......ok
Checking for libssl......ok
Checking for imlib2......ok
Checking for cairo......ok
Checking for harfbuzz......ok
Checking for gegl-0.4......You may need to install the development package of gegl-0.4.
Checking for sqlite3......ok
Checking for readline......ok
Checking for cups......ok

Too many problems to proceed!
Use --force to override. You may have to adjust CPPFLAGS and LDFLAGS in Makefiles,
or pass in includes with --extra-cppflags.

On debian based systems, you might try installing all dependencies with this:
    apt-get install g++ pkg-config libpng12-dev libreadline-dev libx11-dev libxext-dev libxi-dev libxft-dev libcups2-dev libimlib2-dev libfontconfig-dev libfreetype6-dev libssl-dev xutils-dev libgraphicsmagick++1-dev mesa-common-dev libglu1-mesa-dev libftgl-dev libcairo2-dev libharfbuzz-dev
```

Here is what I am doing:
https://github.com/probonopd/laidout/blob/dcf0dd519a43f95dc15f077b722de859aff24f87/.travis.yml

What am I doing wrong?

Full build log:
https://api.travis-ci.org/v3/job/540384607/log.txt

**Comment by tomlechner** [comment]
Part of it is It's trying to use Gegl 0.4 but not finding it. On some recent ubuntu, for instance, there's only gegl 0.3, if that's the case you can pass in `./configure --gegl-version=gegl-0.3`. If you are sure you have gegl 0.4, then you can specifiy where the headers and libs are with `--extra-cppflags="-I/path/to/headers"` and `--extra-ldflags="/path/to/libs"`.

I'm surprised the `--force` option isn't working, it should ignore check results if it is given. 

Also, I see you are passing `--disable-sqlite` to laidout's configure.. if that's true, you should also pass in the same thing to Laxkit's configure. 

When I get done traveling perhaps I can work on the build scripts some more. I had been trying to keep the compile system very simple with plain Makefiles, but I keep adding new dependencies, and my configure script gets a bit cumbersome!

**Comment by probonopd** [comment]
Now running into `./configure: line 213: LAXDIR: command not found`

- https://github.com/probonopd/laidout/blob/00af6ad4203e660632d96fb2992bd968274275b0/.travis.yml
- https://api.travis-ci.org/v3/job/543487666/log.txt

**Comment by tomlechner** [comment]
Oops, I mixed up bash and Makefile syntax, had written $(LAXDIR) when it should have just been $LAXDIR.. Fresh pull should fix.

**Comment by probonopd** [comment]
Can you support `DESTDIR`?

```
./configure --prefix=/usr (...)
sudo make install DESTDIR=$(readlink -f appdir) ; find appdir/
(...)
install -D -m711 laxinput/laxinput /usr/local/bin/laxinput && \
	echo '/usr/local/bin/laxinput' >> install.log
find: ‘appdir/’: No such file or directory
```

I would have expected

```
appdir/usr/bin/laidout
appdir/usr/share/applications/laidout.desktop
...
```

- https://github.com/probonopd/laidout/blob/980739fa867b4fa5a8b08b2f348790e1ed4a2cab/.travis.yml
- https://api.travis-ci.org/v3/job/543492962/log.txt

**Comment by tomlechner** [comment]
Hmm.. try with `./configure --finalprefix=$(readlink -f appdir)`
finalprefix is left over from dealing with a similar (i think) issue building .debs.

**Comment by probonopd** [comment]
`Unrecognized option --finalprefix /home/travis/build/probonopd/laidout/laxkit/appdir`

**Comment by tomlechner** [comment]
Try with the '=' and no spaces:
--finalprefix=/home/...

**Comment by tomlechner** [comment]
I can't seem to get it to fail with --finalprefix with or without the '='.. Do you have the full output?

**Comment by probonopd** [comment]
Sure:
https://api.travis-ci.org/v3/job/543502333/log.txt

Travis CI build script:
https://github.com/probonopd/laidout/blob/5b33aae281c1cb02f590d3566ca2f70cdc1262e0/.travis.yml

**Comment by probonopd** [comment]
> Try with the '=' and no spaces

That is what I've been doing:
https://github.com/probonopd/laidout/blob/5b33aae281c1cb02f590d3566ca2f70cdc1262e0/.travis.yml#L27

**Comment by tomlechner** [comment]
Ok, that's just weird. 
finalprefix is parsed no differently than prefix or anything else. The only difference here is using $(readlink -f appdir). Even if it's an unrecognized option, it shouldn't exit 1. If finalprefix is always known, as a last resort, you can hardcode it in configure, line 12. Does it also fail if you use backticks instead of $(...)?

**Comment by probonopd** [comment]
```
$ ./configure --finalprefix=`pwd`/appdir --laxkit=`pwd`/laxkit/lax --nogl --disable-sqlite --force --gegl-version=gegl-0.3
Unrecognized option --finalprefix /home/travis/build/probonopd/laidout/laxkit/appdir
```

**Comment by probonopd** [comment]
```
$ ./configure --prefix=`pwd`/appdir --laxkit=`pwd`/laxkit/lax --nogl --disable-sqlite --force --gegl-version=gegl-0.3
Unrecognized option --laxkit /home/travis/build/probonopd/laidout/laxkit/laxkit/lax
```

Help!

**Comment by tomlechner** [comment]
Hmm... is that configure being called from laidout/laxkit, or from laidout/ ? I see a cd to laxkit, but maybe not a cd  back out? As it happens, the laxkit/configure aborts on unrecognized options, but Laidout's does not.

**Comment by probonopd** [comment]
Heureka! That was it. Sorry for not having noticed earlier.

Now getting 

```
g++ -std=c++11  -Wall -g -gdwarf-2 -I/home/travis/build/probonopd/laidout/laxkit/lax/.. `pkg-config --cflags freetype2` -I/home/travis/build/probonopd/laidout/src -I/usr/include/GraphicsMagick/  -c -o singleseditor.o singleseditor.cc
polyptychwindow.cc:254:1: error: expected declaration before ‘}’ token
 } // namespace Laidout
 ^
<builtin>: recipe for target 'polyptychwindow.o' failed
make[2]: *** [polyptychwindow.o] Error 1
make[2]: Leaving directory '/home/travis/build/probonopd/laidout/src/impositions'
Makefile:180: recipe for target 'laidout' failed
make[1]: *** [laidout] Error 2
make[1]: Leaving directory '/home/travis/build/probonopd/laidout/src'
Makefile:29: recipe for target 'laidout' failed
make: *** [laidout] Error 2
The command "make -j$(nproc)" exited with 2.
```

https://api.travis-ci.org/v3/job/544056189/log.txt

**Comment by tomlechner** [comment]
That one's easy (i think). Fixed in master. 
Resulting from the --nogl option and a badly nested #ifndef. It's possible there's other minor snags from not building without the opengl parts. Is there a particular reason you are using --nogl?

**Comment by probonopd** [comment]
>  Is there a particular reason you are using --nogl?

I generally try to build things with the minimal amount of dependencies and then go from there. What for would an imposing software need OpenGL?

**Comment by probonopd** [comment]
Getting there, but running into a compile error:

```
polyptychwindow.cc:99:1: error: ‘PolyptychWindow’ does not name a type
 PolyptychWindow::PolyptychWindow(NetImposition *imp, anXWindow *parnt,unsigned long owner,const char *sendmes)
 ^
```

Full log:
https://api.travis-ci.org/v3/job/544573113/log.txt

**Comment by tomlechner** [comment]
Fixed in master.
About gl not useful in layout software, what are you talking about!? Without gl, you can't do this: https://www.flickr.com/photos/tomlechner/3838153212/in/album-72157604986347329/
Though I confess that unwrapper as it exists in Laidout currently is a bit unsatisfactory and buggy. I do need to spend more time on the 3-d stuff.

**Comment by probonopd** [comment]
Thank you, let's see how this build goes:
https://github.com/probonopd/laidout/pull/7

**Comment by tomlechner** [comment]
Almost! Pushed a fix for those nullptr errors.
Looks like g++ not consistently compiling for c++11, I added it explicitly for that directory.

**Comment by probonopd** [comment]
Thank you. Now it does compile :+1:

**Comment by probonopd** [comment]
An AppImage is available for testing at https://github.com/probonopd/laidout/releases/tag/continuous. Please test it and see if it is working correctly. Once everything is working satisfactorily, I will send a pull request. 

Again, thanks for you help!

**Comment by tomlechner** [comment]
Awesome!

It doesn't look like it's finding resources that are supposed to be installed in particular places, normally `prefix/share/laidout/(version)/*`. For instance icons and (currently) one plugin.
It looks like it's trying to look in /home/travis/build/probonopd/laidout/appdir/usr/share/laidout/0.097.1/* but not finding it. How do appimages deal with file references like that?
The default directory it searches in at runtime will normally be that --finalprefix value.

Also, straight from git, when run, Laidout dumps out a large amount of messages to the console. That stuff is great to aid debugging, but final releases would need the `make hidegarbage` command to be run on Laxkit and in Laidout before compiling. To avoid commit hassles, be warned this will change just about every file. The changes are reversible with `make unhidegarbage`.

**Comment by probonopd** [comment]
> It looks like it's trying to look in /home/travis/build/probonopd/laidout/appdir/usr/share/laidout/0.097.1/* but not finding it. How do appimages deal with file references like that?

Since AppImages get mounted at varying mount points, the applications inside AppImages cannot assume a fixed absolute prefix that is determined at compile time but need to use relative paths (relative to the main executable).

Example:
Instead of hardcoding `$PREFIX/share/...` which the compiler translates into `/usr/share/...` one would need to use `(directory in which the main executable resides)/../share/...`. This is called "making the application relocatable".
The result is that if the application happens to reside in `/usr`, it will still work. But if the application resides in another location (as it is in an AppImage), it will _still_ work.

One can resolve `/proc/self/exe` and construct the path from there:
https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe/1024937

Do you think you can make Laidout load its resources from a path relative to the main executable?

**Comment by tomlechner** [comment]
I see. Yes, I can do that, seems easy enough! Might not have time for that till the weekend though.

**Comment by tomlechner** [comment]
Ok, I implemented a "--relocatable" option for both Laidout and Laxkit's configure script. This removes reliance on any hardcoded paths, and looks for things based on /proc/self/exe. You don't have to specify any "--finalprefix", just the "--prefix" and  relocatable option is enough.

**Comment by probonopd** [comment]
Should we enable sqlite? Which advantage would it bring here?

**Comment by probonopd** [comment]
Please check https://github.com/probonopd/laidout/releases/tag/continuous, is it any good?

**Comment by tomlechner** [comment]
Sqlite is only relevant when there's a font database with tags made by Fontmatrix on a user's system, which is probably unlikely. No big deal if it's disabled.

**Comment by probonopd** [comment]
Thanks @tomlechner. Please let me know if the AppImage at https://github.com/probonopd/laidout/releases/tag/continuous works as intended, then I will send a pull request.

**Comment by tomlechner** [comment]
It looks like Laidout's finding the right directories, but it's missing icons. Also missing the geglnodes.so that should be in share/laidout/0.097.1/plugins. That directory is missing, I'm guessing because lack of icons interrupted the install target.

To build the icons requires Inkscape, will that cause a major headache for a CI process?
This can be triggered by doing:
```
cd src/icons
make
cd ../../laxkit/lax/icons
make
cd ../../..
cp laxkit/lax/icons/*png src/icons
```

I've been meaning to make icon preparation better, it's a frequent irritation. I might have default icons in a separate repository at some point. I'm reluctant to have them in the main repo, as they are supposed to (at some point in the future) be generated with configured options or at runtime. They can also be unzipped from this zip: https://github.com/Laidout/laidout/releases/download/0.097/laidout-icons.zip.

**Comment by probonopd** [comment]
> To build the icons requires Inkscape, will that cause a major headache for a CI process?

No, actually I had already added Inkscape as a build-time dependency but had assumed the icons would be built automatically. Let's see how the 8c08929 build goes.

I just notice that generating the icon takes a long time. Maybe the generated icons should be checked into the repository?

**Comment by ghost** [comment]
> I just notice that generating the icon takes a long time.

What about replace Inkscape with sK1/UniConvertor 2.0 for this task?

- https://github.com/sk1project/sk1-wx
  - https://downloads.sk1project.net/sk1/nightbuilds/
  - https://downloads.sk1project.net/uniconvertor/nightbuilds/

**Comment by probonopd** [comment]
The icon stuff adds 10 minutes to the build process, from 3 to 13. Not complaining, just saying.

**Comment by probonopd** [comment]
> Sqlite is only relevant when there's a font database with tags made by Fontmatrix on a user's system

Fontmatrix. Another gem I didn't know about until today. [Needs an AppImage](https://github.com/fontmatrix/fontmatrix/issues/19).

**Comment by probonopd** [comment]
Making progress. Damnit ;-)

![damnit](https://user-images.githubusercontent.com/2480569/59569171-54376280-9075-11e9-96d1-b3379c0cf137.png)

**Comment by tomlechner** [comment]
Yes, icons are a pain point. I'm making a repo just for the icons (done soon).
The time is why I don't have them build by default. Long term goal is to have Laidout itself create the icons at runtime, which will make adapting to hires displays much easier, but my svg importer isn't sufficient yet. Not sure about Uniconverter.

Is the geglnodes.so there, but not loading, or not there at all? 

It's important to have UI elements that are relevant to the situation!

**Comment by probonopd** [comment]
> Is the geglnodes.so there, but not loading, or not there at all?

It is there but its dependencies were not deployed yet, working on it.

**Comment by tomlechner** [comment]
So I made this repository for prebuilt icons: https://github.com/Laidout/laidout-icons
Before laidout `make install`, clone the repo and: `cp laidout-icons/target-24/* src/icons`

**Comment by probonopd** [comment]
Now running into

```
GeglNodesPlugin initializing...
babl-extension.c:204 babl_extension_load()
	dlopen() failed:
	/usr/lib/x86_64-linux-gnu/babl-0.1/CIE.so: undefined symbol: babl_space_from_xyz
When loading /usr/lib/x86_64-linux-gnu/babl-0.1/HCY.so:
	babl-model.c:175 babl_model_new()
	unhandled argument 'alpha' for babl_model 'HCYA'
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
/tmp/babl.gdb:1: Error in sourced command file:
No stack.
```

Apparently the plugin gets loaded, but then it seems to attempt `dlopen()` stuff from `/usr` which is not a good idea at all. Any way to prevent that from happening and only `dlopen()` stuff from locations relative to the main executable?

The GIMP AppImage seems to use a [custom AppRun](https://github.com/aferrero2707/gimp-appimage/blob/722050de6072bf3668d229f0d43aa7a1baab32f2/AppRun.sh#L39-L43) launcher script that sets

```
#!/bin/bash
DIR="`dirname \"$0\"`" 
DIR="`( cd \"$DIR\" && readlink -f $(pwd) )`"
export BABL_PATH=$(readlink -f "$DIR/usr/lib/babl-0.1")
export GEGL_PATH=$(readlink -f "$DIR/usr/lib/gegl-0.4")
```

Maybe we need to do that too.

**Comment by probonopd** [comment]
Is any of the `usr/lib/x86_64-linux-gnu/babl-0.1/` actually needed? Then we need to bundle those and their dependencies as well.

**Comment by probonopd** [comment]
Please try now @tomlechner

**Comment by tomlechner** [comment]
Besides the initial geglnodes.so, I'm not doing any dlopen,  I presume any other library loading is internal to gegl, which absolutely depends on babl. Which is what gimps `export BABL_Path.. ` is supposed to account for, I guess?

When I load on my system, my geglnodes.so seems to load, but somehow it doesn't seem to pull in anything that's from the actual gegl library, as if gegl isn't being initialized or something, and subsequent library calls just return nothing. I might need to put in more error checking for this kind of thing.

Otherwise, looks like icons work now!

**Comment by probonopd** [comment]
> When I load on my system, my geglnodes.so seems to load, but somehow it doesn't seem to pull in anything that's from the actual gegl library, as if gegl isn't being initialized or something, and subsequent library calls just return nothing. I might need to put in more error checking for this kind of thing.

Maybe because the stuff from `usr/lib/x86_64-linux-gnu/gegl-0.4/` and its dependencies would need to be bundled? Which of those are needed? All?

**Comment by tomlechner** [comment]
Potentially all, yes. I imagine they could all be accessible in Laidout's node tool.

**Comment by probonopd** [comment]
Is it better now? How do I test?

**Comment by tomlechner** [comment]
Still missing the gegl nodes. To test, start a new document, shortcut with `laidout -n letter`, select Node Tool from tool menu lower left, right cilck -> Add Node, under Gegl, there should be thirty or so nodes, not just GeglBounds, GeglToImage, ImageToGegl.

In the debug output to the console, there's a line that's "gegl operations:", which should be followed by numerous lines showing each gegl operation. Since there's not, the gegl library is not returning any known operations. Not quite sure what to do about that. I'm not seeing any bad linking messages here.

**Comment by tomlechner** [comment]
In the travis.yml, Laidout is being configured and built against gegl-0.3, but there's a bunch of lines referring to gegl-0.4? `-executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/`

How much of Gimp's apprun is appimage magic, and how much is gimp magic? Laidout should need no particular setup, apparently other than helping gegl and babl find their .so files.

**Comment by probonopd** [comment]
Spot on, that was my mistake.

**Comment by probonopd** [comment]
So I guess this time it's looking better?

![](https://user-images.githubusercontent.com/2480569/59866799-fc05a680-937b-11e9-91af-30b68c884dbf.png)

By the way, there seems to be so much more in Laidout that meets the eye initially, I wish there was a good video to learn it all.

**Comment by tomlechner** [comment]
In that node menu, all the gegl based nodes are under “Gegl”. All the other nodes are native laidout. If libraries are connecting there should be a whole lot under gegl. If broken, there’ll be only maybe three nodes under gegl that are glue between laidout and gegl data. 

These might help: YouTube.com/user/tomsart
No promises about quality or completeness though!

Really I use laidout mostly for a variety of interface experiments. As a general purpose editing platform for vector graphics Laidout’s a bit rough around the edges though. My main goal right now is smoothing that out somewhat.

**Comment by tomlechner** [comment]
I'm not seeing all the gegl nodes in Laidout-57cb006-x86_64.AppImage, only the 3 gegl glue nodes. So a custom apprun would just be a script that sets environment variables for babl and gegl then calls the actual binary?

For reference, when fully successful, the gegl menu should look like this:
![geglnodes](https://user-images.githubusercontent.com/3885958/59968778-32663180-94f4-11e9-8221-018c1fa829ed.png)

**Comment by probonopd** [comment]
I have no clue why it is not loading these. Are there additional environment variables missing? You can run `--appimage-extract` to inspect/change its contents, including `AppRun`, if you'd like to experiment.

**Comment by tomlechner** [comment]
I see in the AppRun, the GEGL_PATH is still set to 0.4, not 0.3.

**Comment by tomlechner** [comment]
If I make changes to the extracted stuff to experiment, what's the reverse of --appimage-extract?

**Comment by probonopd** [comment]
If I make changes to the extracted stuff to experiment, what's the reverse of --appimage-extract?

```
wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
chmod +x ./appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage ./squashfs-root/
```

But just executing `AppRun` in the extracted directory should be sufficient to see if it works.

**Comment by tomlechner** [comment]
Woohoo, success!!

**Comment by probonopd** [comment]
I tried to send a PR but it shows too many changes. I am a bit puzzled.

**Comment by tomlechner** [comment]
Done!
https://github.com/Laidout/laidout/releases/tag/continuous

**Comment by probonopd** [comment]
Thank you very much @tomlechner . Well done! :+1:
